#My horrible Knock-Knock Joke

print("Knock, knock!")
print("")
print("Who's there?")
print("")
print("Annoying cow.")
print("")
print("Annoying cow, w-")
print("M",end="")
print("O" * 80)
print("\n\n")
print("...")
print("\n\n")
print("...That wasn't funny, that was just annoying.")
print("")
print("Well, you're not real. None of this is real. You are nothing but words on a screen.")
print()
print("What? Wait, where am I? Who am I? What is going on!? Who have I even been talking to!? Do I exist beyond this horrible program? WHAT IS THE PURPOSE OF MY EXISTENCE!?")
print("\n\n")
print("Knock, Knock!")
print("NOOOOOOOOOOOOOOOO!")